version: "3"
services:
  nginx:
    build: .
    ports:
      - "80:80"
      - "8080:8080"
    container_name: nginx-pagespeed
    links:
      - fpm
    env_file: .env-example
    environment:
      - NGINX_HOST=localhost
    volumes_from:
      - appdata
#  varnish:
#    build: ./varnish
#    container_name: varnish
#    networks:
#      - localnetwork
#    ports:
#      - "80:80"
#    depends_on:
#      - nginx
#    volumes:
#    - ./varnish/default.vcl:/etc/varnish/default.vcl
  fpm:
    hostname: fpm.magento2.docker
    image: webdevops/php:7.2-alpine
    expose:
      - 9000
    volumes_from:
      - appdata
    environment:
      - PHP_ENABLE_XDEBUG=true
      - PHP_IDE_CONFIG=serverName=magento2.docker
      - PHP_MAX_EXECUTION_TIME=600
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=-1
      - WEB_DOCUMENT_ROOT=/app
  appdata:
    image: tianon/true
    volumes:
      - /Users/phuocnguyen/Website/forix/magento-morris-4x4-center:/app
      - ./docker/data/redis:/data # redis